# Generated by Django 5.0.1 on 2024-01-17 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.abstractbasemodel')),
                ('name', models.CharField(max_length=128)),
            ],
            bases=('news.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.abstractbasemodel')),
                ('text', models.TextField()),
            ],
            bases=('news.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.abstractbasemodel')),
                ('body', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
            bases=('news.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.abstractbasemodel')),
                ('body', models.TextField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new')),
            ],
            bases=('news.abstractbasemodel',),
        ),
        migrations.CreateModel(
            name='New_tag',
            fields=[
                ('abstractbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.abstractbasemodel')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tag')),
            ],
            bases=('news.abstractbasemodel',),
        ),
    ]
